#region Copyright
/*
 * Yadocari\Migrations2\201601120044427_DownloadCount.Designer.cs
 *
 * Copyright (c) 2017 TeamYadocari
 *
 * You can redistribute it and/or modify it under either the terms of
 * the AGPLv3 or YADOCARI binary code license. See the file COPYING
 * included in the YADOCARI package for more in detail.
 *
 */
#endregion

// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace Yadocari.Migrations2
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DownloadCount : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DownloadCount));
        
        string IMigrationMetadata.Id
        {
            get { return "201601120044427_DownloadCount"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
